[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.5
    ZinggJM/GxEPD2 @ ^1.5.0
    ricmoo/QRCode @ ^0.0.1
