#!/usr/bin/env python3
"""
Convert resources/logo.png to a 1-bit C bitmap header for use with Adafruit GFX drawBitmap().

Output: src/logo.h

Bitmap format: rows packed MSB-first to byte boundaries, suitable for PROGMEM.
"""

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

ROOT    = Path(__file__).parent.parent
SRC     = ROOT / "resources" / "logo.png"
DEST    = ROOT / "src" / "logo.h"

# Target size — matches QR code footprint (version 3, scale 3 = 87px)
TARGET_W = 87
TARGET_H = 87

img = Image.open(SRC).convert("L")  # greyscale

# Resize preserving aspect ratio, fitting within target box
img.thumbnail((TARGET_W, TARGET_H), Image.LANCZOS)

# Pad to exact target size (centre on white background)
canvas = Image.new("L", (TARGET_W, TARGET_H), 255)
x_off = (TARGET_W - img.width)  // 2
y_off = (TARGET_H - img.height) // 2
canvas.paste(img, (x_off, y_off))

# Threshold to 1-bit (pixels < 128 → black/1, else white/0)
# Adafruit GFX drawBitmap: 1 = foreground colour, 0 = background
threshold = 128
bytes_per_row = (TARGET_W + 7) // 8
rows = []
for y in range(TARGET_H):
    row_bytes = []
    for byte_idx in range(bytes_per_row):
        byte = 0
        for bit in range(8):
            x = byte_idx * 8 + bit
            if x < TARGET_W:
                px = canvas.getpixel((x, y))
                if px < threshold:
                    byte |= (0x80 >> bit)
        row_bytes.append(byte)
    rows.append(row_bytes)

flat = [b for row in rows for b in row]

lines = []
for i in range(0, len(flat), 12):
    chunk = flat[i:i+12]
    lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk))

bitmap_body = ",\n".join(lines)

header = f"""\
// Auto-generated by tools/convert_logo.py — do not edit manually
// Source: {SRC.name}  →  {TARGET_W}x{TARGET_H} 1-bit bitmap (MSB first, rows padded to bytes)
#pragma once
#include <Arduino.h>

const int16_t LOGO_W = {TARGET_W};
const int16_t LOGO_H = {TARGET_H};

const uint8_t logo_bitmap[] PROGMEM = {{
{bitmap_body}
}};
"""

DEST.write_text(header)
print(f"Written {DEST}  ({TARGET_W}x{TARGET_H}, {len(flat)} bytes)")
